package no.integrasjon.avtale.types;

public enum AvtaleUnderkategori {
    BILFORSIKRING,
    SMART_BILFORSIKRING,
    MOTORSYKKELFORSIKRING,
    MOPEDFORSIKRING,
    BATFORSIKRING,
    CAMPINGVOGNFORSIKRING,
    SNOSCOOTERFORSIKRING,
    TILHENGERFORSIKRING,
}
